### ISSUE TITLE
Using words in the test data to build the embedding matrix

### ISSUE THREAD

**Issue by smb564** [howardhsu/Double-Embeddings-and-CNN-based-Sequence-Labeling-for-Aspect-Extraction#6]
As per my understanding, we are not supposed to take any hint (or any information) from the testing data for the model construction. However, in your implementation, when the word_idx.json is computed, the words in the testing set are also considered. (As per my understanding)

Can you please clarify on this matter.

**Comment by howardhsu** [comment]
It depends on whether your embedding layer is trainable or not. 

Since our embedding layer is not trainable, input examples are essentially in a 3d tenor: (batch_size, sent_length, embedding_dim), where embedding_dim=300+100. (in this case, the original 2d matrix of word indexes just save your memory). You can always build such a 3d tensor (even with fasttext crafted OOV embeddings) no matter how my model will be or how the vocab of training/testing will be (the vocab should be much larger or can be totally removed but I just build a small one to cover the dataset). So my model doesn't aware of any testing data ahead, but only use the features word2vec provided that can be similar between seen words in training and unseen words in testing (that's why word2vec is so powerful).

In the other case of trainable embeddings, you need a training vocab (exclude unseen words validation). Embeddings are weights specific to your model and its part of your model. Making unseen words in vocab still cannot let testing data seen to training (since training data do not have unseen words), what is worse is embeddings for those unseen words never changed (features are inconsistent now).

I personally think the first case is more common where the training data is small and you want the power of word2vec from seen words to unseen words, that's the way word2vec supposed to be used. The second case typically assumes the training data is large, then word2vec has little help compared to just using the randomly initialized of embedding layer.

**Comment by smb564** [comment]
Thanks for the informative clarification. I really appreciate that! It really makes sense now. As you've mentioned we can completely remove the idea of an embedding layer and treat embedded tokens as the input to the model.
